In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
ds=pd.read_csv("Market_Basket_Optimisation.csv")
ds

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   object
 1   almonds            5746 non-null   object
 2   avocado            4388 non-null   object
 3   vegetables mix     3344 non-null   object
 4   green grapes       2528 non-null   object
 5   whole weat flour   1863 non-null   object
 6   yams               1368 non-null   object
 7   cottage cheese     980 non-null    object
 8   energy drink       653 non-null    object
 9   tomato juice       394 non-null    object
 10  low fat yogurt     255 non-null    object
 11  green tea          153 non-null    object
 12  honey              86 non-null     object
 13  salad              46 non-null     object
 14  mineral water      24 non-null     object
 15  salmon             7 non-null      object
 16  antioxydant juice  3 non-null      object
 17  frozen smoothie    3 non-null      object
 18  spinach            2 non-null      object
 19  olive oil          0 non-null      float64
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [4]:
# fetching non zero values
transactions=[]
for i in range(0,len(ds)):
    transactions.append([str(ds.values[i,j]) for j in range(0,20) if str(ds.values[i,j])!="0"])

In [5]:
transactions[:3]

[['burgers',
  'meatballs',
  'eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['chutney',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'avocado',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan']]

In [6]:
!pip install apyori

Requirement already satisfied: apyori in c:\users\ravip\anaconda3\lib\site-packages (1.1.2)

In [7]:
from apyori import apriori
rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.3,min_lift=2,min_length=2,max_length=2)
results=list(rules)
results

[RelationRecord(items=frozenset({'bacon', 'spaghetti'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bacon'}), items_add=frozenset({'spaghetti'}), confidence=0.36923076923076925, lift=2.120391094357404)]),
 RelationRecord(items=frozenset({'blueberries', 'spaghetti'}), support=0.0034666666666666665, ordered_statistics=[OrderedStatistic(items_base=frozenset({'blueberries'}), items_add=frozenset({'spaghetti'}), confidence=0.37681159420289856, lift=2.1639256941207803)]),
 RelationRecord(items=frozenset({'body spray', 'french fries'}), support=0.004266666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'body spray'}), items_add=frozenset({'french fries'}), confidence=0.37209302325581395, lift=2.1768312592968835)]),
 RelationRecord(items=frozenset({'chocolate', 'tomato sauce'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'chocolate'}), confidence=0.3584905660377358, lift=2.1876967007998527)]),
 RelationRecord(items=frozenset({'cider', 'eggs'}), support=0.004266666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cider'}), items_add=frozenset({'eggs'}), confidence=0.4050632911392405, lift=2.2536904180595725)]),
 RelationRecord(items=frozenset({'cider', 'milk'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cider'}), items_add=frozenset({'milk'}), confidence=0.31645569620253167, lift=2.441787779340522)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005866666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287)]),
 RelationRecord(items=frozenset({'extra dark chocolate', 'mineral water'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'mineral water'}), confidence=0.47777777777777775, lift=2.0052229061742213)]),
 RelationRecord(items=frozenset({'flax seed', 'green tea'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flax seed'}), items_add=frozenset({'green tea'}), confidence=0.338235294117647, lift=2.562388591800356)]),
 RelationRecord(items=frozenset({'green beans', 'spaghetti'}), support=0.0034666666666666665, ordered_statistics=[OrderedStatistic(items_base=frozenset({'green beans'}), items_add=frozenset({'spaghetti'}), confidence=0.4, lift=2.2970903522205206)]),
 RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096)]),
 RelationRecord(items=frozenset({'ground beef', 'spaghetti'}), support=0.0392, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.39891451831750335, lift=2.2908567284695827)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528)]),
 RelationRecord(items=frozenset({'soup', 'milk'}), support=0.0152, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'milk'}), confidence=0.3007915567282322, lift=2.320922505619076)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'milk'}), support=0.009866666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'milk'}), confidence=0.334841628959276, lift=2.583654544438858)]),
 RelationRecord(items=frozenset({'mineral water', 'nonfat milk'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'nonfat milk'}), items_add=frozenset({'mineral water'}), confidence=0.48717948717948717, lift=2.044681675347596)]),
 RelationRecord(items=frozenset({'olive oil', 'spaghetti'}), support=0.022933333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'spaghetti'}), confidence=0.3488843813387424, lift=2.0035473660341254)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151)]),
 RelationRecord(items=frozenset({'pepper', 'spaghetti'}), support=0.009866666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pepper'}), items_add=frozenset({'spaghetti'}), confidence=0.37185929648241206, lift=2.1354860058331475)]),
 RelationRecord(items=frozenset({'red wine', 'spaghetti'}), support=0.010266666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red wine'}), items_add=frozenset({'spaghetti'}), confidence=0.36492890995260663, lift=2.0956866957462097)]),
 RelationRecord(items=frozenset({'strong cheese', 'spaghetti'}), support=0.0037333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'strong cheese'}), items_add=frozenset({'spaghetti'}), confidence=0.48275862068965514, lift=2.7723504250937316)]),
 RelationRecord(items=frozenset({'tomato sauce', 'spaghetti'}), support=0.006266666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'spaghetti'}), confidence=0.44339622641509435, lift=2.546302984772747)])]

In [8]:
def inspect(results):
    lhs=[tuple(i[2][0][0])[0] for i in results]
    rhs=[tuple(i[2][0][1])[0] for i in results]
    support=[i[1] for i in results]
    confidence=[i[2][0][2] for i in results]
    lift=[i[2][0][3] for i in results]
    return list(zip(lhs,rhs,support,confidence,lift))
data=pd.DataFrame(inspect(results),columns=["Item1","Item2","Support","confidence","lift"])
data

                   Item1          Item2   Support  confidence      lift
0                  bacon      spaghetti  0.003200    0.369231  2.120391
1            blueberries      spaghetti  0.003467    0.376812  2.163926
2             body spray   french fries  0.004267    0.372093  2.176831
3           tomato sauce      chocolate  0.005067    0.358491  2.187697
4                  cider           eggs  0.004267    0.405063  2.253690
5                  cider           milk  0.003333    0.316456  2.441788
6   mushroom cream sauce       escalope  0.005733    0.300699  3.790327
7                  pasta       escalope  0.005867    0.372881  4.700185
8   extra dark chocolate  mineral water  0.005733    0.477778  2.005223
9              flax seed      green tea  0.003067    0.338235  2.562389
10           green beans      spaghetti  0.003467    0.400000  2.297090
11         herb & pepper    ground beef  0.016000    0.323450  3.291555
12           ground beef      spaghetti  0.039200    0.398915  2.290857
13          tomato sauce    ground beef  0.005333    0.377358  3.840147
14                  soup           milk  0.015200    0.300792  2.320923
15     whole wheat pasta           milk  0.009867    0.334842  2.583655
16           nonfat milk  mineral water  0.005067    0.487179  2.044682
17             olive oil      spaghetti  0.022933    0.348884  2.003547
18                 pasta         shrimp  0.005067    0.322034  4.514494
19                pepper      spaghetti  0.009867    0.371859  2.135486
20              red wine      spaghetti  0.010267    0.364929  2.095687
21         strong cheese      spaghetti  0.003733    0.482759  2.772350
22          tomato sauce      spaghetti  0.006267    0.443396  2.546303

In [9]:
#top-10 prodects
data.nlargest(n=10,columns="lift")

                   Item1        Item2   Support  confidence      lift
7                  pasta     escalope  0.005867    0.372881  4.700185
18                 pasta       shrimp  0.005067    0.322034  4.514494
13          tomato sauce  ground beef  0.005333    0.377358  3.840147
6   mushroom cream sauce     escalope  0.005733    0.300699  3.790327
11         herb & pepper  ground beef  0.016000    0.323450  3.291555
21         strong cheese    spaghetti  0.003733    0.482759  2.772350
15     whole wheat pasta         milk  0.009867    0.334842  2.583655
9              flax seed    green tea  0.003067    0.338235  2.562389
22          tomato sauce    spaghetti  0.006267    0.443396  2.546303
5                  cider         milk  0.003333    0.316456  2.441788